# Generated by Django 5.2.4 on 2025-08-06 16:11

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_url_image_image"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterModelTable(
            name="vendor",
            table="vendor",
        ),
    ]
