# Generated by Django 5.2.4 on 2025-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_vendor_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderproducts",
            name="image",
            field=models.TextField(max_length=500),
        ),
    ]
