# Generated by Django 5.2.4 on 2025-08-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_cartorder_order_status_alter_product_life_and_more"),
        ("core", "0006_alter_cartorderproducts_image"),
    ]

    operations = []
